# Generated by Django 4.2.6 on 2023-11-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_new_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('narxi', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField()),
                ('tolovSumma', models.IntegerField(default=0)),
                ('tolovSanasi', models.DateField()),
                ('tolovqilinganmi', models.BooleanField(default=True)),
            ],
        ),
    ]
