# Generated by Django 4.2.6 on 2023-11-30 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexnews',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='indexnews',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
