# Generated by Django 4.2.6 on 2023-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_indexnews_options_alter_indexnews_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorynews',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='singlenews',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='trandingnews',
            options={'ordering': ['-data']},
        ),
    ]
